name = "cf-worker"
type = "javascript"

account_id = ""
workers_dev = true
# route = ""
# zone_id = ""

compatibility_date = "2022-05-09"
compatibility_flags = []

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"


[vars]
UPSTASH_REDIS_REST_URL = "REPLACE_THIS"
UPSTASH_REDIS_REST_TOKEN = "REPLACE_THIS"
