name: Prerelease
on:
  push:
    branches:
      - main
jobs:
  prerelease:
    name: Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

   
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install bun
        run: npm install -g bun

      - name: Build
        run: bun run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
        working-directory: dist
        
