name: Tests
on:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      # - uses: denoland/setup-deno@v1
      #   with:
      #     deno-version: v1.x
      - run: curl -fsSL https://deno.land/x/install/install.sh | sh
      - run: echo "$HOME/.deno/bin" > $GITHUB_PATH

      - name: Verify formatting
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Build
        run: deno run -A ./cmd/build.ts

      - name: Size limit
        run: node_modules/.bin/size-limit
        working-directory: dist

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        algorithm: ["fixedWindow", "slidingWindow", "tokenBucket"]
        scope: ["global", "region"]
    name: Tests
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      # - uses: denoland/setup-deno@v1
      #   with:
      #     deno-version: v1.x
      - run: curl -fsSL https://deno.land/x/install/install.sh | sh

      - run: echo "$HOME/.deno/bin" > $GITHUB_PATH

      - name: Start redis server
        uses: ./.github/actions/redis
        with:
          UPSTASH_REDIS_REST_URL: http://127.0.0.1:6379
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          UPSTASH_REPO_ACCESS_TOKEN: ${{ secrets.UPSTASH_REPO_ACCESS_TOKEN }}
          REDIS_SERVER_CONFIG: ${{ secrets.REDIS_SERVER_CONFIG }}

      - name: Run tests
        run: deno test -A --fail-fast --shuffle ./src
        env:
          UPSTASH_REDIS_REST_URL: http://127.0.0.1:6379
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          UPSTASH_TEST_ALGORITHM: ${{ matrix.algorithm }}
          UPSTASH_TEST_SCOPE: ${{ matrix.scope }}
          EU2_UPSTASH_REDIS_REST_URL: ${{ secrets.EU2_UPSTASH_REDIS_REST_URL }}
          EU2_UPSTASH_REDIS_REST_TOKEN: ${{ secrets.EU2_UPSTASH_REDIS_REST_TOKEN }}
          APN_UPSTASH_REDIS_REST_URL: ${{ secrets.APN_UPSTASH_REDIS_REST_URL }}
          APN_UPSTASH_REDIS_REST_TOKEN: ${{ secrets.APN_UPSTASH_REDIS_REST_TOKEN }}
          US1_UPSTASH_REDIS_REST_URL: ${{ secrets.US1_UPSTASH_REDIS_REST_URL }}
          US1_UPSTASH_REDIS_REST_TOKEN: ${{ secrets.US1_UPSTASH_REDIS_REST_TOKEN }}
